services:
    nginx:
        image: "815090125753.dkr.ecr.us-east-1.amazonaws.com/lost-found/nginx:latest"
        container_name: nginx
        networks:
            - django-networks
        ports:
            - "80:80"
        restart: always
        depends_on:
            - django-app
    django-app:
        image: "815090125753.dkr.ecr.us-east-1.amazonaws.com/lost-found/backend:latest"
        container_name: django-app
        networks:
            - django-networks
        ports:
            - "8000:8000"
        restart: always
        healthcheck:
            test: ["CMD", "curl", "-f", "localhost:8000"]
            interval: 1m30s
            timeout: 30s
            retries: 5
            start_period: 30s
networks:
    django-networks:
        
