services:
    nginx:
        build:
            context: ./nginx
        container_name: nginx
        networks:
            - django-networks
        ports:
            - "80:80"
        restart: always
        depends_on:
            - django-app
    django-app:
        build: 
            context: .
        container_name: django-app
        networks:
            - django-networks
        ports:
            - "8000:8000"
        restart: always
        healthcheck:
            test: ["CMD", "curl", "-f", "localhost:8000"]
            interval: 1m30s
            timeout: 30s
            retries: 5
            start_period: 30s
networks:
    django-networks:
        
