kind: Deployment
apiVersion: apps/v1
metadata:
  name: lostfound-deployment
  namespace: lost-and-found
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lost-and-found
  template:
    metadata:
      name: lost-and-found
      labels:
        app: lost-and-found
    spec:
      containers:
      - name: lost-and-found
        image: parthsingh2496/lostfound-image:latest
        ports:
        - containerPort: 8000
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 300m
            memory: 256Mi
