kind: HorizontalPodAutoscaler
apiVersion: autoscaling/v2
metadata:
  name: lostfound-hpa 
  namespace: lost-and-found

spec:
  scaleTargetRef:
    kind: Deployment
    apiVersion: apps/v1
    name: lostfound-deployment
  
  minReplicas: 3
  maxReplicas: 6

  metrics:
  - type: Resource 
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 40
