# Generated by Django 5.2.8 on 2025-11-20 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_founditem_alter_lostitems_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='founditem',
            name='category',
            field=models.CharField(choices=[('Phone', 'Phone'), ('Wallet', 'Wallet'), ('Bag', 'Bag'), ('Laptop', 'Laptop'), ('Keys', 'Keys'), ('Other', 'Other')], default='Other', max_length=50),
        ),
        migrations.AddField(
            model_name='lostitems',
            name='category',
            field=models.CharField(choices=[('Phone', 'Phone'), ('Wallet', 'Wallet'), ('Bag', 'Bag'), ('Laptop', 'Laptop'), ('Keys', 'Keys'), ('Other', 'Other')], default='Other', max_length=50),
        ),
    ]
