# Generated by Django 5.2.8 on 2025-11-21 18:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0005_claim'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='claim',
            name='claimant_user',
        ),
        migrations.RemoveField(
            model_name='claim',
            name='message',
        ),
        migrations.RemoveField(
            model_name='claim',
            name='reporter_user',
        ),
        migrations.AddField(
            model_name='founditem',
            name='finder_email',
            field=models.CharField(default='bob@example.com', max_length=50),
        ),
        migrations.AddField(
            model_name='founditem',
            name='finder_name',
            field=models.CharField(default='Bob', max_length=50),
        ),
        migrations.AddField(
            model_name='founditem',
            name='finder_phone',
            field=models.CharField(default='9876543210', max_length=15),
        ),
        migrations.AddField(
            model_name='lostitems',
            name='reporter_email',
            field=models.CharField(default='alice@example.com', max_length=50),
        ),
        migrations.AddField(
            model_name='lostitems',
            name='reporter_name',
            field=models.CharField(default='Alice', max_length=50),
        ),
        migrations.AddField(
            model_name='lostitems',
            name='reporter_phone',
            field=models.CharField(default='1234567890', max_length=15),
        ),
        migrations.AlterField(
            model_name='claim',
            name='found_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reports.founditem'),
        ),
        migrations.AlterField(
            model_name='claim',
            name='lost_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reports.lostitems'),
        ),
        migrations.AlterField(
            model_name='claim',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20),
        ),
    ]
