# Generated by Django 5.2.8 on 2025-11-21 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0006_remove_claim_claimant_user_remove_claim_message_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='founditem',
            name='finder_email',
        ),
        migrations.RemoveField(
            model_name='founditem',
            name='finder_name',
        ),
        migrations.RemoveField(
            model_name='founditem',
            name='finder_phone',
        ),
        migrations.RemoveField(
            model_name='lostitems',
            name='reporter_email',
        ),
        migrations.RemoveField(
            model_name='lostitems',
            name='reporter_name',
        ),
        migrations.RemoveField(
            model_name='lostitems',
            name='reporter_phone',
        ),
    ]
