name: Deploy to AWS ECR

on:
  push:
    branches:
      - main

jobs:

  

  backend:
    uses: ./.github/workflows/ecr-build-push.yaml
    with:
      service_name: lost-found/backend  #ECR repo name
      docker_context: .
      dockerfile_path: ./Dockerfile
      image_tag: v1.0.${{ github.run_number }}
    secrets: inherit
