name: Reusable ECR Build & Push

on:
  workflow_call:
    inputs:
      service_name:
        required: true
        type: string

      docker_context:
        required: true
        type: string

      dockerfile_path:
        required: false
        type: string
        default: Dockerfile

      image_tag:
        required: false
        type: string
        default: latest

    secrets:
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true
      AWS_REGION:
        required: true
      AWS_ECR_REGISTRY:
        required: true

jobs:
  build-push:
    runs-on: ubuntu-latest

    env:
      AWS_ECR_REGISTRY: ${{ secrets.AWS_ECR_REGISTRY }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build Docker Image
        run: |
          set -e

          docker build \
            -f ${{ inputs.dockerfile_path }} \
            -t ${{ inputs.service_name }}:${{ inputs.image_tag }} \
            ${{ inputs.docker_context }}

      - name: Tag Image
        run: |
          set -e

          docker tag \
            ${{ inputs.service_name }}:${{ inputs.image_tag }} \
            $AWS_ECR_REGISTRY/${{ inputs.service_name }}:${{ inputs.image_tag }}

          docker tag \
            ${{ inputs.service_name }}:${{ inputs.image_tag }} \
            $AWS_ECR_REGISTRY/${{ inputs.service_name }}:latest

      - name: Push Image
        run: |
          set -e

          docker push \
            $AWS_ECR_REGISTRY/${{ inputs.service_name }}:${{ inputs.image_tag }}

          docker push \
            $AWS_ECR_REGISTRY/${{ inputs.service_name }}:latest
